# Generated by Django 5.2.6 on 2025-11-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mon_app_ecommerce", "0002_emailverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Payment"),
                    ("paid", "Paid"),
                    ("failed", "Payment Failed"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
