# Generated by Django 5.2.7 on 2025-11-03 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mon_app_ecommerce", "0004_seller_product_seller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
